**Basic Python**

1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
n=s.split()
print(s)

Hi there Sam!


2.Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
txt="The diameter of {} is {} kilometers."
print(txt.format(planet,diameter))

The diameter of Earth is 12742 kilometers.


3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


4.Numpy

In [7]:
import numpy as np

4.1 Create an array of 10 zeros?

4.2 Create an array of 10 fives?

In [9]:

array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [11]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Concatinate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=a+b
print(c)

[5 7 9]


Pandas

8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd

In [15]:
data={10,20,30}
df=pd.DataFrame(data,columns=['Numbers'])
df

Numbers
0       10
1       20
2       30

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
import datetime
import pandas as pd
date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
k=10
date_generated = pd.date_range(date,periods=k)
print(date_generated.strftime("%d-%m-%Y"))


Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023'],
      dtype='object')


10. Create 2D list to DataFrame

In [18]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['no','name','score'])
print(df)

   no name  score
0   1  aaa     22
1   2  bbb     25
2   3  ccc     24
